### ISSUE TITLE
ggplot2的一些小函数

### ISSUE THREAD

**Issue by GuangchuangYu** [YuLab-SMU/ggfun#1]
之前在rvcheck包里藏了一些诸如get_aes_var之类的小函数，是因为rvcheck这个包基本上没有什么依赖（依赖它不产生其它额外的依赖），而这些小函数又想在不同的包里使用。

现在有了这个ggfun包，它可以作为我们放ggplot2小工具的地方。像rvcheck里的函数已经移过来。
@xiangpin @huerqiang @nyzhoulang 大家如果有依赖这些函数，依赖关系更改一下，改为ggfun。

并且有一些小函数，要请放过来，这样在我们不同的包里，需要调用的话，不会增加额外的依赖。

小函数加进来首先要依赖关系简单，然后这个可以做为我们画图的基础包。像ggtree里一些调整facet之类的函数，后面也考虑搬过来。

**Comment by GuangchuangYu** [comment]
rvcheck在github上的版本，已经删除，你们都应该装github版本，然后在check自己包的时候，就会发现问题，就可以更正到新的包的依赖了。

rvcheck中另一些小函数搬到了yulab.utils包中，也上cran了。

**Comment by GuangchuangYu** [comment]
@xiangpin @huerqiang @nyzhoulang 赶紧更新。

**Comment by huerqiang** [comment]
好的，老师，我今晚更新一下。

**Comment by nyzhoulang** [comment]
已经check完毕，`ggmsa`中没有依赖`rvcheck`。
另外发现`seqcombo`的[hybrid_plot()](https://github.com/YuLab-SMU/seqcombo/blob/master/R/reassortment.R)有依赖rvcheck，不过这部分代码没有迁移到`ggmsa`中。
